config/routes.rb
Rails.application.routes.draw do
  get 'account/signup' => "signup#index", as: :signup_index
  post 'signup/create_user'

  #get 'home/index' 

  root 'home#index'

  resource :signup

  resource :home

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
	validates_presence_of :full_name, :email, :password
	validates_length_of :full_name, minimum: 3, maximum: 20 
	validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
	# has_secure_password
	validates_confirmation_of :password, :message => "should match confirmation"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index 
  end
end

app/controllers/signup_controller.rb
class SignupController < ApplicationController
  def index
  	@user = User.new
  end

  def create_user
  	@user = User.new(user_params)
  	if @user.save
  		redirect_to signup_index_path
  	else
  		redirect_to signup_index_path
  	end
  end


  private

  def user_params
  	params.require(:user).permit(:full_name, :email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/signup_helper.rb
module SignupHelper
end

app/views/home/index.html.erb
<!-- add-products -->
	<div class="add-products">  
		<div class="container">
			<div class="add-products-row">
				<div class="w3ls-add-grids">
					<a href="menu.html"> 
						<h4>Get <span>20%<br>Cashback</span></h4>
						<h5>Ordered in mobile app only </h5>
						<h6>Order Now <i class="fa fa-arrow-circle-right" aria-hidden="true"></i></h6>
					</a>
				</div>
				<div class="w3ls-add-grids w3ls-add-grids-right">
					<a href="menu.html"> 
						<h4>GET Upto<span><br>40% Offer</span></h4>
						<h5>Sunday special discount</h5>
						<h6>Order Now <i class="fa fa-arrow-circle-right" aria-hidden="true"></i></h6>
					</a>
				</div> 
				<div class="clearfix"> </div> 
			</div>  	 
		</div>
	</div>
	<!-- //add-products --> 
	<!-- order -->   	
	<div class="wthree-order">  
		<!-- <img src="images/i2.jpg" class="w3order-img" alt=""/> -->
		<%= image_tag "i2.jpg", class: "w3order-img" %>
		<div class="container">
			<h3 class="w3ls-title">How To Order Online Food</h3>
			<p class="w3lsorder-text">Get your favourite food in 4 simple steps.</p>
			<div class="order-agileinfo">  
				<div class="col-md-3 col-sm-3 col-xs-6 order-w3lsgrids"> 
					<div class="order-w3text"> 
						<i class="fa fa-map" aria-hidden="true"></i> 
						<h5>Search Area</h5>
						<span>1</span>
					</div>
				</div>
				<div class="col-md-3 col-sm-3 col-xs-6 order-w3lsgrids"> 
					<div class="order-w3text"> 
						<i class="fa fa-cutlery" aria-hidden="true"></i> 
						<h5>Choose Food</h5>
						<span>2</span>
					</div>
				</div>
				<div class="col-md-3 col-sm-3 col-xs-6 order-w3lsgrids"> 
					<div class="order-w3text"> 
						<i class="fa fa-credit-card" aria-hidden="true"></i>
						<h5>Pay Money</h5>
						<span>3</span>
					</div>
				</div>
				<div class="col-md-3 col-sm-3 col-xs-6 order-w3lsgrids"> 
					<div class="order-w3text"> 
						<i class="fa fa-truck" aria-hidden="true"></i>
						<h5>Enjoy Food</h5>
						<span>4</span>
					</div>
				</div>
				<div class="clearfix"> </div> 
			</div>
		</div>
	</div>
	<!-- //order -->    
	<!-- deals -->
	<div class="w3agile-deals">
		<div class="container">
			<h3 class="w3ls-title">Special Services</h3>
			<div class="dealsrow">
				<div class="col-md-6 col-sm-6 deals-grids">
					<div class="deals-left">
						<i class="fa fa-truck" aria-hidden="true"></i>
					</div> 
					<div class="deals-right">
						<h4>FREE DELIVERY</h4>
						<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce tempus justo ac </p>
					</div> 
					<div class="clearfix"> </div>
				</div> 
				<div class="col-md-6 col-sm-6 deals-grids">
					<div class="deals-left">
						<i class="fa fa-birthday-cake" aria-hidden="true"></i>
					</div> 
					<div class="deals-right">
						<h4>Party Orders</h4>
						<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce tempus justo ac </p>
					</div> 
					<div class="clearfix"> </div>
				</div>
				<div class="col-md-6 col-sm-6 deals-grids">
					<div class="deals-left">
						<i class="fa fa-users" aria-hidden="true"></i>
					</div> 
					<div class="deals-right">
						<h4>Team up Scheme</h4>
						<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce tempus justo ac </p>
					</div>
					<div class="clearfix"> </div>
				</div> 
				<div class="col-md-6 col-sm-6 deals-grids">
					<div class="deals-left">
						<i class="fa fa-building" aria-hidden="true"></i>
					</div> 
					<div class="deals-right">
						<h4>corporate orders</h4>
						<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce tempus justo ac </p>
					</div>
					<div class="clearfix"> </div>
				</div> 
				<div class="clearfix"> </div>
			</div>
		</div>
	</div>
	<!-- //deals --> 
	<!-- dishes -->
	<div class="w3agile-spldishes">
		<div class="container">
			<h3 class="w3ls-title">Special Foods</h3>
			<div class="spldishes-agileinfo">
				<div class="col-md-3 spldishes-w3left">
					<h5 class="w3ltitle">Staple Specials</h5>
					<p>Vero vulputate enim non justo posuere placerat Phasellus mauris vulputate enim non justo enim .</p>
				</div> 
				<div class="col-md-9 spldishes-grids">
					<!-- Owl-Carousel -->
					<div id="owl-demo" class="owl-carousel text-center agileinfo-gallery-row">
						<a href="products.html" class="item g1">
							<!-- <img class="lazyOwl" src="images/g1.jpg" title="Our latest gallery" alt=""/> -->
							<%= image_tag "g1.jpg", class: "lazyOwl" %>
							<div class="agile-dish-caption">
								<h4>Duis congue</h4>
								<span>Neque porro quisquam est qui dolorem </span>
							</div>
						</a>
						<a href="products.html" class="item g1">
							<!-- <img class="lazyOwl" src="images/g2.jpg" title="Our latest gallery" alt=""/> -->
							<%= image_tag "g2.jpg", class: "lazyOwl" %>
							<div class="agile-dish-caption">
								<h4>Duis congue</h4>
								<span>Neque porro quisquam est qui dolorem </span>
							</div>
						</a>
						<a href="products.html" class="item g1">
							<!-- <img class="lazyOwl" src="images/g3.jpg" title="Our latest gallery" alt=""/> -->
							<%= image_tag "g3.jpg", class: "lazyOwl" %>
							<div class="agile-dish-caption">
								<h4>Duis congue</h4>
								<span>Neque porro quisquam est qui dolorem </span>
							</div>
						</a>
						<a href="products.html" class="item g1">
							<!-- <img class="lazyOwl" src="images/g4.jpg" title="Our latest gallery" alt=""/> -->
							<%= image_tag "g4.jpg", class: "lazyOwl" %>
							<div class="agile-dish-caption">
								<h4>Duis congue</h4>
								<span>Neque porro quisquam est qui dolorem </span>
							</div>
						</a>
						<a href="products.html" class="item g1">
							<!-- <img class="lazyOwl" src="images/g5.jpg" alt=""/> -->
							<%= image_tag "g5.jpg", class: "lazyOwl" %>
							<div class="agile-dish-caption">
								<h4>Duis congue</h4>
								<span>Neque porro quisquam est qui dolorem </span>
							</div>
						</a> 
						<a href="products.html" class="item g1">
							<!-- <img class="lazyOwl" src="images/g1.jpg" title="Our latest gallery" alt=""/> -->
							<%= image_tag "g1.jpg", class: "lazyOwl" %>
							<div class="agile-dish-caption">
								<h4>Duis congue</h4>
								<span>Neque porro quisquam est qui dolorem </span>
							</div>
						</a>
						<a href="products.html" class="item g1">
							<!-- <img class="lazyOwl" src="images/g2.jpg" title="Our latest gallery" alt=""/> -->
							<%= image_tag "g2.jpg", class: "lazyOwl" %>
							<div class="agile-dish-caption">
								<h4>Duis congue</h4>
								<span>Neque porro quisquam est qui dolorem </span>
							</div>
						</a>
						<a href="products.html" class="item g1">
							<!-- <img class="lazyOwl" src="images/g3.jpg" title="Our latest gallery" alt=""/> -->
							<%= image_tag "g3.jpg", class: "lazyOwl" %>
							<div class="agile-dish-caption">
								<h4>Duis congue</h4>
								<span>Neque porro quisquam est qui dolorem </span>
							</div>
						</a>
					</div> 
				</div>  
				<div class="clearfix"> </div>
			</div>
		</div>
	</div>
	<!-- //dishes --> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  	<head>
	    <title>Food Web</title>
	    <meta name="viewport" content="width=device-width, initial-scale=1">
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />

		<script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>

	    <%= csrf_meta_tags %> 

	    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
	    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

	    <link href="//fonts.googleapis.com/css?family=Berkshire+Swash" rel="stylesheet"> 
		<link href="//fonts.googleapis.com/css?family=Yantramanav:100,300,400,500,700,900" rel="stylesheet">
  	</head>



  	<body>

  		<!-- banner -->
		<div class="banner">
			<!-- header -->
			<div class="header">
				<div class="w3ls-header"><!-- header-one --> 
					<div class="container">
						<div class="w3ls-header-left">
							<p>Find your awesome food before you traveling</p>
						</div>
						<div class="w3ls-header-right">
							<ul> 
								<li class="head-dpdn">
									<i class="fa fa-phone" aria-hidden="true"></i> Call us: +880 1714 698 679
								</li> 
								<li class="head-dpdn">
									<a href="login.html"><i class="fa fa-sign-in" aria-hidden="true"></i> Login</a>
								</li> 
								<li class="head-dpdn">
									<a href="<%= signup_index_path %>"><i class="fa fa-user-plus" aria-hidden="true"></i> Signup</a>
								</li> 
								<li class="head-dpdn">
									<a href="help.html"><i class="fa fa-question-circle" aria-hidden="true"></i> Help</a>
								</li>
							</ul>
						</div>
						<div class="clearfix"> </div> 
					</div>
				</div>
				<!-- //header-one -->    
				<!-- navigation -->
				<div class="navigation agiletop-nav">
					<div class="container">
						<nav class="navbar navbar-default">
							<!-- Brand and toggle get grouped for better mobile display -->
							<div class="navbar-header w3l_logo">
								<button type="button" class="navbar-toggle collapsed navbar-toggle1" data-toggle="collapse" data-target="#bs-megadropdown-tabs">
									<span class="sr-only">Toggle navigation</span>
									<span class="icon-bar"></span>
									<span class="icon-bar"></span>
									<span class="icon-bar"></span>
								</button>  
								<h1><a href="<%= root_url %>">Awesome Food<span>The Best Food Collection</span></a></h1>
							</div> 
							<div class="collapse navbar-collapse" id="bs-megadropdown-tabs">
								<ul class="nav navbar-nav navbar-right">
									<li><a href="<%= root_url %>" class="active">Home</a></li>	
									<!-- Mega Menu -->
									<li class="dropdown">
										<a href="#" class="dropdown-toggle" data-toggle="dropdown">Cities <b class="caret"></b></a>
										<ul class="dropdown-menu multi-column columns-3">
											<div class="row">
												<div class="col-sm-4">
													<ul class="multi-column-dropdown">
														<h6>City</h6> 
														<li><a href="sylhet.html">Sylhet</a></li> 
														<li><a href="dhaka.html">Dhaka</a></li> 
														<li><a href="khulna.html">Khulna</a></li> 
														<li><a href="rajshahi.html">Rajshahi</a></li> 
													</ul>
												</div>
												<div class="clearfix"></div>
											</div>
										</ul>
									</li>
									<li><a href="about.html">About</a></li> 
									<li><a href="contact.html">Contact Us</a></li>
								</ul>
							</div>
						</nav>
					</div>
				</div>
				<!-- //navigation --> 
			</div>
			<!-- //header-end --> 
	    
			<!-- banner-text -->
			<div class="banner-text">	
				<div class="container">
	        <div class="banner_text_main">
	          <h2>Delicious food from the <br> <span>Best Chefs For you.</span></h2>
	          <div class="agileits_search">
	            <form action="#" method="post">
	              <input name="Search" type="text" placeholder="Enter Your Area Name" required="">
	              <input type="submit" value="Search">
	            </form>
	          </div> 
	        </div>
				</div>
			</div>
		</div>
		<!-- //banner --> 


    	<%= yield %>


    	<!-- subscribe -->
		<div class="subscribe agileits-w3layouts"> 
			<div class="container">
				<div class="col-md-6 social-icons w3-agile-icons">
					<h4>Keep in touch</h4>  
					<ul>
						<li><a href="#" class="fa fa-facebook icon facebook"> </a></li>
						<li><a href="#" class="fa fa-twitter icon twitter"> </a></li>
						<li><a href="#" class="fa fa-google-plus icon googleplus"> </a></li>
						<li><a href="#" class="fa fa-dribbble icon dribbble"> </a></li>
						<li><a href="#" class="fa fa-rss icon rss"> </a></li> 
					</ul> 
				</div> 
				<div class="col-md-6 subscribe-right">
					<h3 class="w3ls-title">Subscribe to Our <br><span>Newsletter</span></h3>  
					<form action="#" method="post"> 
						<input type="email" name="email" placeholder="Enter your Email..." required="">
						<input type="submit" value="Subscribe">
						<div class="clearfix"> </div> 
					</form>  
					<!-- <img src="images/i1.png" class="sub-w3lsimg" alt=""/> -->
					<%= image_tag "i1.png", class: "sub-w3lsimg" %>
				</div>
				<div class="clearfix"> </div> 
			</div>
		</div>
		<!-- //subscribe --> 
		<!-- footer -->
		<div class="footer agileits-w3layouts">
			<div class="container">
				<div class="w3_footer_grids">
					<div class="col-xs-6 col-sm-3 footer-grids w3-agileits">
						<h3>company</h3>
						<ul>
							<li><a href="about.html">About Us</a></li>
							<li><a href="contact.html">Contact Us</a></li>  
							<li><a href="careers.html">Careers</a></li>  
							<li><a href="help.html">Partner With Us</a></li>   
						</ul>
					</div> 
					<div class="col-xs-6 col-sm-3 footer-grids w3-agileits">
						<h3>help</h3>
						<ul>
							<li><a href="faq.html">FAQ</a></li> 
							<li><a href="login.html">Returns</a></li>   
							<li><a href="login.html">Order Status</a></li> 
							<li><a href="offers.html">Offers</a></li> 
						</ul>  
					</div>
					<div class="col-xs-6 col-sm-3 footer-grids w3-agileits">
						<h3>policy info</h3>
						<ul>  
							<li><a href="terms.html">Terms & Conditions</a></li>  
							<li><a href="privacy.html">Privacy Policy</a></li>
							<li><a href="login.html">Return Policy</a></li> 
						</ul>   
					</div>
					<div class="col-xs-6 col-sm-3 footer-grids w3-agileits">
						<h3>Menu</h3> 
						<ul>
							<li><a href="menu.html">All Day Menu</a></li> 
							<li><a href="menu.html">Lunch</a></li>
							<li><a href="menu.html">Dinner</a></li>
							<li><a href="menu.html">Flavours</a></li> 
						</ul>  
					</div> 
					<div class="clearfix"> </div>
				</div>
			</div> 
		</div>
		<div class="copyw3-agile"> 
			<div class="container">
				<p>&copy; 2017 Awesome Food. All rights reserved</p>
			</div>
		</div>
		<!-- //footer --> 


		<script type="text/javascript">
			jQuery(document).ready(function($) {
				$(".scroll").click(function(event){		
					event.preventDefault();
			
			$('html,body').animate({scrollTop:$(this.hash).offset().top},1000);
				});
			});

			$(document).ready(function() {
				/*
				var defaults = {
					containerID: 'toTop', // fading element id
					containerHoverID: 'toTopHover', // fading element hover id
					scrollSpeed: 1200,
					easingType: 'linear' 
				};
				*/
				
				$().UItoTop({ easingType: 'easeOutQuart' });
			});

			$(document).ready(function() {
				$("#owl-demo").owlCarousel ({
					items : 3,
					lazyLoad : true,
					autoPlay : true,
					pagination : true,
				});
			});
		</script>

  	</body>


</html>

app/views/signup/index.html.erb
<!-- breadcrumb -->  
	<div class="container">	
		<ol class="breadcrumb w3l-crumbs">
			<li><a href="<%= root_url %>"><i class="fa fa-home"></i> Home</a></li> 
			<li class="active">Sign Up</li>
		</ol>
	</div>
	<!-- //breadcrumb -->
	<!-- sign up-page -->
	<div class="login-page about">
		<!-- <img class="login-w3img" src="images/img3.jpg" alt=""> -->
		<%= image_tag "img3.jpg", class: "login-w3img" %>
		<div class="container"> 
			<h3 class="w3ls-title w3ls-title1">Sign Up to your account</h3>  
			<div class="login-agileinfo"> 
				<%= form_for @user, url: signup_create_user_path, validate: true do |f| %>

					<%= f.text_field :full_name, class: "agile-ltext", placeholder: "Full Name" %>

					<%= f.email_field :email, class: "agile-ltext", placeholder: "Email" %>

					<%= f.password_field :password, class: "agile-ltext", placeholder: "Password" %>
					<%= f.password_field :password_confirmation, class: "agile-ltext", placeholder: "Password" %>

					<!--<div class="wthreelogin-text"> 
						<ul> 
							<li>
								<label class="checkbox"><input type="checkbox" name="checkbox"><i></i> 
									<span> I agree to the terms of service</span> 
								</label> 
							</li> 
						</ul>
						<div class="clearfix"> </div>
					</div>-->   
					<%= f.submit 'Sign Up' %>
				<% end %>
				<p>Already have an account?  <a href="login.html"> Login Now!</a></p> 
			</div>	 
		</div>
	</div>
	<!-- //sign up-page --> 